### PR TITLE
Support version string comparison operators

### PR DESCRIPTION
**Pull request by palmsey**
Adds support for version string comparison operators.

This is a port of the original feature implementation in Growthbook 2.2.

Addresses https://github.com/alippo-com/GrowthBook-SDK-Flutter/issues/53

### CODE REVIEW

**Comment by DK070202** [comment]
Thanks @palmsey for this, I have gone through this, and the changes look good to me but test cases for the  `paddedVersionString` are missing in `gb_utils_test`.  Post that this is good to go.

**Comment by palmsey** [comment]
@DK070202 thanks, I've updated the tests to cover the new method.

**Review by dhruvinnv — APPROVED** [review]
LGTM

**Comment by DK070202** [comment]
@princebansal

**Comment by palmsey** [comment]
@princebansal @DK070202 just checking in since it's been a few months. I would like to use this feature. Is there anything I can do to help get this released?

**Review by princebansal — APPROVED** [review]

**Comment by dhruvinnv** [comment]
@palmsey we have merged this branch to our repo and we will be releasing new version soon, till then you can refer SDK as direct repo, in your dependency.

**Pull request merged**
